### ISSUE TITLE
Link for SimpleWorkflow gives access denied error

### ISSUE THREAD

**Issue by MattJColes** [aws-samples/amazon-lex-connect-workshop#3]
Link for SimpleWorkflow gives access denied error in Lab 2 - bucket permissions?

https://s3-eu-west-1.amazonaws.com/connect-lex-lab/Workflows.zip

**Comment by yongsushi** [comment]
You can simply clone and get the file from this repo directly, 
https://github.com/aws-samples/amazon-lex-connect-workshop/blob/master/lab2-Building_Connect_Call_Center/Simple_Workflow
